# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Legend of the Green Dragon
version: "1.0.7"
slug: lotgd
description: Remake of the classic Legend of the Green Dragon RPG.
url: "https://github.com/NB-Core/lotgd"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
  - addon_config:rw
ports:
  80/tcp: 80
ingress: true
panel_icon: mdi:dragon
options:
  db_host: core-mariadb
  db_name: lotgd
  db_user: lotgd
  db_password: ""
  db_use_data_cache: false
schema:
  db_host: str
  db_name: str
  db_user: str
  db_password: password
  db_use_data_cache: bool
    #image: "ghcr.io/nb-core/{arch}-addon-lotgd"
