#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
# ==============================================================================
# Initialize Luanti server configuration
# Reads add-on options and writes /data/luanti.conf
# ==============================================================================

declare server_name
declare server_description
declare server_port
declare max_users
declare enable_pvp
declare enable_damage
declare creative_mode
declare time_speed
declare world_name
declare gameid
declare disallow_empty_password

bashio::log.info "Configuring Luanti server..."

server_name=$(bashio::config 'server_name')
server_description=$(bashio::config 'server_description')
server_port=$(bashio::config 'server_port')
max_users=$(bashio::config 'max_users')
enable_pvp=$(bashio::config 'enable_pvp')
enable_damage=$(bashio::config 'enable_damage')
creative_mode=$(bashio::config 'creative_mode')
time_speed=$(bashio::config 'time_speed')
world_name=$(bashio::config 'world_name')
gameid=$(bashio::config 'gameid')
disallow_empty_password=$(bashio::config 'disallow_empty_password')

# Validate world_name to prevent path traversal attacks
if [[ ! "${world_name}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    bashio::log.fatal "Invalid world_name '${world_name}': only letters, digits, hyphens and underscores are allowed."
    exit 1
fi

# Strip newlines from string values to prevent config-file injection
server_name="${server_name//$'\n'/}"
server_name="${server_name//$'\r'/}"
server_description="${server_description//$'\n'/}"
server_description="${server_description//$'\r'/}"
gameid="${gameid//$'\n'/}"
gameid="${gameid//$'\r'/}"

# Ensure required data directories exist
mkdir -p "/data/worlds/${world_name}"

# Ensure shared mod and game directories exist
mkdir -p /share/luanti/mods
mkdir -p /share/luanti/games

# Write the server configuration file using printf to avoid heredoc expansion risks
{
    printf '# Luanti server configuration\n'
    printf '# Generated by Home Assistant add-on - edit options in the HA UI instead.\n\n'
    printf 'server_name = %s\n' "${server_name}"
    printf 'server_description = %s\n' "${server_description}"
    printf 'port = %s\n' "${server_port}"
    printf 'max_users = %s\n' "${max_users}"
    printf 'enable_pvp = %s\n' "${enable_pvp}"
    printf 'enable_damage = %s\n' "${enable_damage}"
    printf 'creative_mode = %s\n' "${creative_mode}"
    printf 'time_speed = %s\n' "${time_speed}"
    printf 'disallow_empty_password = %s\n' "${disallow_empty_password}"
    printf '\ngameid = %s\n' "${gameid}"
    printf '\n# Mod search paths\n'
    printf 'modspath = /data/mods\n'
    printf 'modspath = /share/luanti/mods\n'
    printf '\n# Additional game search path\n'
    printf 'gamepath = /share/luanti/games\n'
} > /data/luanti.conf

# Append optional settings only when they have a non-empty value.
# Strip newlines/carriage-returns to prevent config-file injection.
if bashio::config.has_value 'server_password'; then
    server_password=$(bashio::config 'server_password')
    server_password="${server_password//$'\n'/}"
    server_password="${server_password//$'\r'/}"
    printf 'server_password = %s\n' "${server_password}" >> /data/luanti.conf
fi

if bashio::config.has_value 'motd'; then
    motd=$(bashio::config 'motd')
    motd="${motd//$'\n'/}"
    motd="${motd//$'\r'/}"
    printf 'motd = %s\n' "${motd}" >> /data/luanti.conf
fi

bashio::log.info "Luanti configuration written to /data/luanti.conf"
bashio::log.info "World directory: /data/worlds/${world_name}"
