#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
# ==============================================================================
# Initialize Luanti server configuration
# Reads add-on options and writes /data/luanti.conf
# ==============================================================================

declare server_name
declare server_description
declare server_port
declare max_users
declare enable_pvp
declare enable_damage
declare creative_mode
declare time_speed
declare world_name
declare game_id
declare disallow_empty_password

bashio::log.info "Configuring Luanti server..."

server_name=$(bashio::config 'server_name')
server_description=$(bashio::config 'server_description')
server_port=$(bashio::config 'server_port')
max_users=$(bashio::config 'max_users')
enable_pvp=$(bashio::config 'enable_pvp')
enable_damage=$(bashio::config 'enable_damage')
creative_mode=$(bashio::config 'creative_mode')
time_speed=$(bashio::config 'time_speed')
world_name=$(bashio::config 'world_name')
game_id=$(bashio::config 'game_id')
disallow_empty_password=$(bashio::config 'disallow_empty_password')

# Validate world_name to prevent path traversal attacks
if [[ ! "${world_name}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    bashio::log.fatal "Invalid world_name '${world_name}': only letters, digits, hyphens and underscores are allowed."
    exit 1
fi

# Strip newlines from string values to prevent config-file injection
server_name="${server_name//$'\n'/}"
server_name="${server_name//$'\r'/}"
server_description="${server_description//$'\n'/}"
server_description="${server_description//$'\r'/}"
game_id="${game_id//$'\n'/}"
game_id="${game_id//$'\r'/}"

# Ensure required data directories exist
mkdir -p "/data/worlds/${world_name}"

# Ensure shared mod and game directories exist
mkdir -p /share/luanti/mods
mkdir -p /share/luanti/games

# Write the server configuration file using printf to avoid heredoc expansion risks
{
    printf '# Luanti server configuration\n'
    printf '# Generated by Home Assistant add-on - edit options in the HA UI instead.\n\n'
    printf 'server_name = %s\n' "${server_name}"
    printf 'server_description = %s\n' "${server_description}"
    printf 'port = %s\n' "${server_port}"
    printf 'max_users = %s\n' "${max_users}"
    printf 'enable_pvp = %s\n' "${enable_pvp}"
    printf 'enable_damage = %s\n' "${enable_damage}"
    printf 'creative_mode = %s\n' "${creative_mode}"
    printf 'time_speed = %s\n' "${time_speed}"
    printf 'disallow_empty_password = %s\n' "${disallow_empty_password}"
    printf 'default_game = %s\n' "${game_id}"
    printf '\n# Mod search paths\n'
    printf 'modspath = /data/mods\n'
    printf 'modspath = /share/luanti/mods\n'
    printf '\n# Additional game search path\n'
    printf 'gamepath = /share/luanti/games\n'
} > /data/luanti.conf

# Check if we should use PostgreSQL (defaulting to enabled if service present)
# The 'postgresql' service is required in config.yaml so bashio::services should work
if bashio::services.available "postgresql"; then
    host=$(bashio::services "postgresql" "host")
    port=$(bashio::services "postgresql" "port")
    username=$(bashio::services "postgresql" "username")
    password=$(bashio::services "postgresql" "password")
    # Use a safe database name
    dbname="luanti_data"
    
    bashio::log.info "Configuring PostgreSQL connection..."
    
    # Ensure database exists
    # Redirect stdout to /dev/null to avoid confusing logs, but keep errors
    if ! PGPASSWORD="${password}" psql -h "${host}" -p "${port}" -U "${username}" -lqt | cut -d \| -f 1 | grep -qw "${dbname}"; then
        bashio::log.info "Creating database '${dbname}'..."
        PGPASSWORD="${password}" psql -h "${host}" -p "${port}" -U "${username}" -c "CREATE DATABASE \"${dbname}\"" >/dev/null
    fi
    
    # We need to construct the connection string for world.mt
    # NOTE: Minetest expects 'pgsql_connection' in world.mt, not minetest.conf usually, 
    # but we can try to put defaults here or manage world.mt directly.
    # Since world.mt is world-specific, we should check/create it.
    
    world_mt="/data/worlds/${world_name}/world.mt"
    conn_str="host=${host} port=${port} user=${username} password=${password} dbname=${dbname}"
    
    if [ ! -f "${world_mt}" ]; then
        bashio::log.info "Creating ${world_mt} with PostgreSQL backend..."
        cat > "${world_mt}" <<EOF
# generic backend setting
backend = postgresql
# specific backend settings
auth_backend = postgresql
player_backend = postgresql
# connection strings
pgsql_connection = ${conn_str}
pgsql_auth_connection = ${conn_str}
pgsql_player_connection = ${conn_str}
gameid = ${game_id}
world_name = ${world_name}
EOF
    else
        bashio::log.warning "World config ${world_mt} already exists. Enforcing PostgreSQL backend..."
        # Simple sed replacement to switch backend. Migration is NOT performed automatically here.
        # Users must migrate manually if they have existing SQLite data.
        sed -i "s/^backend = .*/backend = postgresql/" "${world_mt}"
        sed -i "s/^auth_backend = .*/auth_backend = postgresql/" "${world_mt}"
        sed -i "s/^player_backend = .*/player_backend = postgresql/" "${world_mt}"
        
        # Remove old connection strings if any and append new ones
        sed -i "/^pgsql_connection/d" "${world_mt}"
        sed -i "/^pgsql_auth_connection/d" "${world_mt}"
        sed -i "/^pgsql_player_connection/d" "${world_mt}"
        
        printf "pgsql_connection = %s\n" "${conn_str}" >> "${world_mt}"
        printf "pgsql_auth_connection = %s\n" "${conn_str}" >> "${world_mt}"
        printf "pgsql_player_connection = %s\n" "${conn_str}" >> "${world_mt}"
    fi
else
    bashio::log.warning "PostgreSQL service not available! Falling back to SQLite integration (not recommended)..."
    {
        printf '\n# SQLite settings\n'
        # Use synchronous = 0 (OFF) to prevent "database is locked" errors on docker volumes
        printf 'sqlite_synchronous = 0\n'
    } >> /data/luanti.conf
fi

# Append optional settings only when they have a non-empty value.
# Strip newlines/carriage-returns to prevent config-file injection.
if bashio::config.has_value 'server_password'; then
    server_password=$(bashio::config 'server_password')
    server_password="${server_password//$'\n'/}"
    server_password="${server_password//$'\r'/}"
    printf 'server_password = %s\n' "${server_password}" >> /data/luanti.conf
fi

if bashio::config.has_value 'motd'; then
    motd=$(bashio::config 'motd')
    motd="${motd//$'\n'/}"
    motd="${motd//$'\r'/}"
    printf 'motd = %s\n' "${motd}" >> /data/luanti.conf
fi

bashio::log.info "Luanti configuration written to /data/luanti.conf"
bashio::log.info "World directory: /data/worlds/${world_name}"
